/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_tmatesoft_svn_core_internal_wc_SVNStatHelper */

#ifndef _Included_org_tmatesoft_svn_core_internal_wc_SVNStatHelper
#define _Included_org_tmatesoft_svn_core_internal_wc_SVNStatHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_tmatesoft_svn_core_internal_wc_SVNStatHelper
 * Method:    getType
 * Signature: (Ljava/lang/String;Z)I
 */
JNIEXPORT jint JNICALL Java_org_tmatesoft_svn_core_internal_wc_SVNStatHelper_getType
  (JNIEnv *, jclass, jstring, jboolean);

#ifdef __cplusplus
}
#endif
#endif
