/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_tmatesoft_svn_core_internal_wc_SVNStatHelper */

#ifndef _Included_org_tmatesoft_svn_core_internal_wc_SVNStatHelper
#define _Included_org_tmatesoft_svn_core_internal_wc_SVNStatHelper
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jint JNICALL Java_org_tmatesoft_svn_core_internal_wc_SVNStatHelper_getType
  (JNIEnv *, jclass, jstring, jboolean);

JNIEXPORT jint JNICALL Java_org_tmatesoft_svn_core_internal_wc_SVNStatHelper_changeMode
  (JNIEnv *, jclass, jstring, jboolean, jboolean, jboolean, jboolean);

JNIEXPORT jint JNICALL Java_org_tmatesoft_svn_core_internal_wc_SVNStatHelper_link
  (JNIEnv *, jclass, jstring, jstring);

JNIEXPORT jstring JNICALL Java_org_tmatesoft_svn_core_internal_wc_SVNStatHelper_getLinkTargetPath
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
