#!/bin/sh

cygwin=false;
case "`uname`" in
  CYGWIN*) cygwin=true ;;
esac

JAVASVN_HOME=`dirname $0`
JAVASVN_HOME=`cd "$JAVASVN_HOME" ; pwd`

JAVASVN_CP=$JAVASVN_HOME/javasvn.jar:$JAVASVN_HOME/javasvn-cli.jar:$JAVASVN_HOME/jsch.jar:$JAVASVN_HOME/commons-codec-1.3.jar:$JAVASVN_HOME/commons-httpclient-3.0-rc3.jar:$JAVASVN_HOME/commons-logging.jar

if $cygwin ; then
  JAVASVN_CP=`cygpath --windows --path "$JAVASVN_CP"`
  [ -n "$JAVASVN_LOGDIR" ] &&
    JAVASVN_LOGDIR=`cygpath --unix "$JAVASVN_LOGDIR"`
fi

if [ ! -d $JAVASVN_LOGDIR ]; then
	mkdir $JAVASVN_LOGDIR
fi

JAVASVN_VM_OPTIONS=-Djava.util.logging.config.file=$JAVASVN_HOME/logging.properties

#
# uncomment the line below to make JavaSVN use jakarta httpclient instead of built in http implementation.
#
#JAVASVN_VM_OPTIONS=$JAVASVN_VM_OPTIONS -Djavasvn.httpclient=jakarta
#

JAVASVN_MAINCLASS=org.tmatesoft.svn.cli.SVN
$JAVA_HOME/bin/java $JAVASVN_VM_OPTIONS -cp $JAVASVN_CP $JAVASVN_MAINCLASS "$@"
